add help message if chrome can't be found

diff --git a/src/tagui b/src/tagui
--- a/src/tagui
+++ b/src/tagui
@@ -213,10 +213,14 @@ headless_switch=""; if [ "$tagui_web_browser" == "headless" ]; then headless_swi
 # check for which operating system and launch chrome accordingly
 chrome_started="$(uname -s)"; chrome_switches="--remote-debugging-port=9222 about:blank"
 if [ "$chrome_started" == "Darwin" ]; then
-if ! [ -f "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" ]; then echo "ERROR - cannot find Chrome at \"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome\""; exit 1; fi
+if ! [ -f "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" ]; then
+echo "ERROR - cannot find Chrome at \"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome\""
+echo "Chrome is at a non-standard location on your macOS, raise an issue on TagUI GitHub page"; exit 1; fi
 pkill Google\ Chrome; /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome $chrome_switches $window_size $headless_switch > /dev/null 2>&1 &
 else
-if ! type "$chrome_command" > /dev/null; then echo "ERROR - cannot find Chrome command \"$chrome_command\""; exit 1; fi
+if ! type "$chrome_command" > /dev/null; then
+echo "ERROR - cannot find Chrome command \"$chrome_command\""
+echo "update chrome_command setting in tagui/src/tagui and make sure symlink to command is created"; exit 1; fi
 pkill $chrome_command; $chrome_command $chrome_switches $window_size $headless_switch > /dev/null 2>&1 &
 fi
 
